version: '3.7'
services:
  postgres:
    image: postgres:10.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=healme
    logging:
      options:
        max-size: 10m
        max-file: "3"
    network_mode: host
